// Ajouter ces styles à la fin du getStyles function dans GroupChat.js

  modalOverlay: {
    flex: 1,
    backgroundColor: "#00000066",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  modalCard: {
    width: "100%",
    maxWidth: 520,
    backgroundColor: "#fff",
    borderRadius: 28,
    padding: 18,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: theme.colors.text,
  },
  modalClose: {
    fontSize: 20,
    fontWeight: "700",
    color: theme.colors.text,
  },
  userListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: "#f5f5f5",
  },
  userAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  userAvatarText: {
    color: "#fff",
    fontWeight: "700",
  },
  userName: {
    fontWeight: "700",
    color: theme.colors.text,
  },
  userEmail: {
    color: theme.colors.subtext,
    fontSize: 12,
    marginTop: 2,
  },
  searchInput: {
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    color: theme.colors.text,
  },
  searchResultItem: {
    backgroundColor: "#f5f5f5",
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
  },
  searchResultUser: {
    fontWeight: "700",
    color: theme.colors.primary,
    fontSize: 12,
  },
  searchResultMessage: {
    color: theme.colors.text,
    marginTop: 4,
  },
  searchResultTime: {
    color: theme.colors.subtext,
    fontSize: 11,
    marginTop: 4,
  },
